version: 2
jobs:
  build:
    docker:
      - image: idubrov/rust-stm32:latest
    environment:
      - RUSTFLAGS: "-C link-dead-code"
    steps:
      - checkout
      - run: cargo +stable build
      - run: cargo +stable test --all
      - run: cargo +nightly build
      - run: cargo +nighly test --all
      - run: cargo +nightly clippy
      - run: cargo +nightly kcov
      - run:
          name: Uploading code coverage
          command: |
              bash <(curl -s https://codecov.io/bash)
